sensor_ip: 10.8.0.3
host_ip: 10.8.0.6
host_udp_port: 0
frame_id: sick_laser
skip: 0
angle_start: 0
angle_end: 0
time_offset: 0.0
channel_enabled: True
general_system_state: True
derived_settings: True
measurement_data: True
intrusion_data: True
application_io_data: True
use_persistent_config: False
