sensor_ip: 10.1.0.5
host_ip: 10.1.0.4
host_udp_port: 0
frame_id: lidar_1
skip: 0
angle_start: 0
angle_end: 0
time_offset: 0.0
channel_enabled: True
general_system_state: True
derived_settings: True
measurement_data: True
intrusion_data: True
application_io_data: True
use_persistent_config: False
